### ISSUE TITLE
Any Update?

### ISSUE THREAD

**Issue by zhuyb00** [savinienb/OnlyCaps-Net#1]
Hi, I saw your paper in MICCA and was surpurised by your interesting idea. 
Looking forward to see your code as soon as possible!

**Comment by savinienb** [comment]
Hello,

Thank you for your interest in our paper and code.
I m currently traveling and will not be able to upload the code until mid-October.

Best,
Savinien

**Comment by savinienb** [comment]
Hi again,

The code is now online.
Enjoy :)
